# Generated by Django 4.2.16 on 2024-11-21 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managebanks', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_loan_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='managebanks.creditloanoption')),
                ('jeonse_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='managebanks.jeonseoption')),
                ('mortgage_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='managebanks.mortgageoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_loan_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='managebanks.creditloanoption')),
                ('jeonse_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='managebanks.jeonseoption')),
                ('mortgage_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='managebanks.mortgageoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'credit_loan_option'), ('user', 'jeonse_option'), ('user', 'mortgage_option')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='creditlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='creditlike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='creditlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jeonsecomment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='jeonsecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='jeonselike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jeonselike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='jeonselike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mortgagecomment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mortgagecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='mortgagelike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mortgagelike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mortgagelike',
            name='user',
        ),
        migrations.DeleteModel(
            name='CreditComment',
        ),
        migrations.DeleteModel(
            name='CreditLike',
        ),
        migrations.DeleteModel(
            name='JeonseComment',
        ),
        migrations.DeleteModel(
            name='JeonseLike',
        ),
        migrations.DeleteModel(
            name='MortgageComment',
        ),
        migrations.DeleteModel(
            name='MortgageLike',
        ),
    ]
